### ISSUE TITLE
how to compress the html code in vue file?

### ISSUE THREAD

**Issue by HoldSkill** [centrual/cordova-template-framework7-vue-webpack#23]
hello, how to compress the html code in vue file? should i change the configure of webpack.config.js?thank you~

**Comment by centrual** [comment]
Compression means gzip, rar, zip etc. Why compression needed also how is related with this template?

If you asking minify, when you add --release to the command, it's automatically adds uglify js, so your javascript files become uglified ( uglify = minify + naming obfuscate ). Also everytime it minifies generated html file.

**Comment by HoldSkill** [comment]
````
cordova run browser -- --live-reload --release
````
i try to use this code to test my project 
![image](https://cloud.githubusercontent.com/assets/25190239/24245834/784ccd7a-0fff-11e7-9dfd-460b442e87e4.png)
as you can see, when i use that code to compress, it seems to not work. but i can use the HtmlWebpackPlugin to compress html code, then these five div can display inline-block.

**Comment by HoldSkill** [comment]
thanks for your help, have a greate day~

**Comment by centrual** [comment]
edit like that:
``` css
.actionBox {
  display: block;
  box-sizing: border-box !important;
}

.action {
  box-sizing: border-box !important;
}
```
